// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package catalogpages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/eduexchange/eduexchange/internal/middleware"
	"github.com/eduexchange/eduexchange/internal/templ/components"
	"github.com/eduexchange/eduexchange/internal/templ/layouts"
)

type ExportData struct {
	AuthUser *middleware.AuthUser
}

func (d ExportData) username() string {
	if d.AuthUser != nil {
		return d.AuthUser.Username
	}
	return ""
}

func (d ExportData) userRole() string {
	if d.AuthUser != nil && len(d.AuthUser.Roles) > 0 {
		return d.AuthUser.Roles[0]
	}
	return ""
}

func ExportPage(data ExportData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = components.PageHeader("Export Resources", []components.Breadcrumb{
				{Label: "Export"},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" <div style=\"max-width:520px;\"><div style=\"background:var(--surface-elevated);border:1px solid var(--border-default);border-radius:10px;padding:28px;box-shadow:var(--shadow-sm);\"><h2 style=\"font-size:1rem;font-weight:600;margin:0 0 8px;\">Export Resource Metadata</h2><p style=\"font-size:0.875rem;color:var(--text-secondary);margin-bottom:20px;\">Download a CSV file containing metadata for all resources (id, title, description, author, category, status, tags, timestamps). File attachments are not included.</p><form method=\"POST\" action=\"/export/generate\"><button type=\"submit\" class=\"ee-btn ee-btn--primary\">Generate &amp; Download CSV</button></form></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base(layouts.PageData{
			Title:       "Export Resources",
			ActiveRoute: "/export",
			Username:    data.username(),
			UserRole:    data.userRole(),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
