// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package moderationpages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/eduexchange/eduexchange/internal/middleware"
	"github.com/eduexchange/eduexchange/internal/templ/layouts"
	"github.com/google/uuid"
)

// BanFormData holds data for the ban form page.
type BanFormData struct {
	TargetUserID   uuid.UUID
	TargetUsername string
	AuthUser       *middleware.AuthUser
}

func (d BanFormData) banFormUsername() string {
	if d.AuthUser != nil {
		return d.AuthUser.Username
	}
	return ""
}

func (d BanFormData) banFormUserRole() string {
	if d.AuthUser != nil && len(d.AuthUser.Roles) > 0 {
		return d.AuthUser.Roles[0]
	}
	return ""
}

func (d BanFormData) isAdmin() bool {
	if d.AuthUser == nil {
		return false
	}
	for _, r := range d.AuthUser.Roles {
		if r == "ADMIN" {
			return true
		}
	}
	return false
}

// BanFormPage renders the ban form.
func BanFormPage(data BanFormData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div style=\"max-width:480px;margin:0 auto;\"><div style=\"margin-bottom:24px;\"><h1 style=\"font-size:1.5rem;font-weight:700;color:var(--text-primary);\">Ban User</h1><p style=\"font-size:0.875rem;color:var(--text-secondary);margin-top:4px;\">User: ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.TargetUsername)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/ban_form.templ`, Line: 53, Col: 105}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div><div style=\"background:var(--surface-elevated);border-radius:8px;padding:24px;border:1px solid var(--border-default);\"><form hx-post=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs("/moderation/users/" + data.TargetUserID.String() + "/ban")
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/ban_form.templ`, Line: 57, Col: 73}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-swap=\"none\" style=\"display:flex;flex-direction:column;gap:16px;\"><div><label style=\"font-size:0.875rem;font-weight:500;color:var(--text-primary);display:block;margin-bottom:6px;\">Ban Duration</label> <select name=\"ban_type\" style=\"width:100%;padding:10px;border-radius:6px;border:1px solid var(--border-default);background:var(--surface-primary);color:var(--text-primary);font-size:0.875rem;\"><option value=\"1_DAY\">1 Day</option> <option value=\"7_DAYS\">7 Days</option> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.isAdmin() {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<option value=\"PERMANENT\">Permanent</option>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</select></div><div><label style=\"font-size:0.875rem;font-weight:500;color:var(--text-primary);display:block;margin-bottom:6px;\">Reason</label> <textarea name=\"reason\" rows=\"4\" placeholder=\"Describe the reason for this ban...\" style=\"width:100%;padding:10px;border-radius:6px;border:1px solid var(--border-default);background:var(--surface-primary);color:var(--text-primary);font-size:0.875rem;resize:vertical;\"></textarea></div><button type=\"submit\" style=\"padding:10px 20px;background:#DC2626;color:white;border:none;border-radius:6px;font-size:0.875rem;cursor:pointer;font-weight:600;\">Apply Ban</button></form></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base(layouts.PageData{
			Title:       "Ban User",
			ActiveRoute: "/moderation",
			Username:    data.banFormUsername(),
			UserRole:    data.banFormUserRole(),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
