// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package moderationpages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/eduexchange/eduexchange/internal/middleware"
	"github.com/eduexchange/eduexchange/internal/model"
	"github.com/eduexchange/eduexchange/internal/templ/layouts"
)

// ReportDetailData holds data for the report detail page.
type ReportDetailData struct {
	Report   *model.Report
	Actions  []model.ModerationAction
	AuthUser *middleware.AuthUser
}

func (d ReportDetailData) username() string {
	if d.AuthUser != nil {
		return d.AuthUser.Username
	}
	return ""
}

func (d ReportDetailData) userRole() string {
	if d.AuthUser != nil && len(d.AuthUser.Roles) > 0 {
		return d.AuthUser.Roles[0]
	}
	return ""
}

// ReportDetailPage renders the report detail view.
func ReportDetailPage(data ReportDetailData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div style=\"margin-bottom:24px;display:flex;align-items:center;gap:16px;\"><a href=\"/moderation/reports\" style=\"color:var(--text-secondary);text-decoration:none;font-size:0.875rem;\">← Back to Queue</a><h1 style=\"font-size:1.5rem;font-weight:700;color:var(--text-primary);\">Report Detail</h1></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if data.Report != nil {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div style=\"display:grid;grid-template-columns:1fr 1fr;gap:24px;\"><!-- Report Info --><div style=\"background:var(--surface-elevated);border-radius:8px;padding:20px;border:1px solid var(--border-default);\"><h2 style=\"font-size:1rem;font-weight:600;color:var(--text-primary);margin-bottom:16px;\">Report Information</h2><dl style=\"display:grid;row-gap:12px;\"><div><dt style=\"font-size:0.75rem;color:var(--text-tertiary);text-transform:uppercase;margin-bottom:2px;\">Resource</dt><dd style=\"font-size:0.875rem;color:var(--text-primary);\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Report.ResourceTitle)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 50, Col: 92}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</dd></div><div><dt style=\"font-size:0.75rem;color:var(--text-tertiary);text-transform:uppercase;margin-bottom:2px;\">Reporter</dt><dd style=\"font-size:0.875rem;color:var(--text-primary);\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var4 string
				templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.Report.ReporterName)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 54, Col: 91}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</dd></div><div><dt style=\"font-size:0.75rem;color:var(--text-tertiary);text-transform:uppercase;margin-bottom:2px;\">Reason</dt><dd style=\"font-size:0.875rem;color:var(--text-primary);\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var5 string
				templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.Report.ReasonType)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 58, Col: 89}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</dd></div><div><dt style=\"font-size:0.75rem;color:var(--text-tertiary);text-transform:uppercase;margin-bottom:2px;\">Status</dt><dd>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = reportStatusBadge(data.Report.Status).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</dd></div><div><dt style=\"font-size:0.75rem;color:var(--text-tertiary);text-transform:uppercase;margin-bottom:2px;\">Description</dt><dd style=\"font-size:0.875rem;color:var(--text-secondary);\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 string
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(data.Report.Description)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 68, Col: 92}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</dd></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if data.Report.ReviewerName != "" {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><dt style=\"font-size:0.75rem;color:var(--text-tertiary);text-transform:uppercase;margin-bottom:2px;\">Reviewer</dt><dd style=\"font-size:0.875rem;color:var(--text-primary);\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var7 string
					templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(data.Report.ReviewerName)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 73, Col: 92}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</dd></div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				if data.Report.Notes != "" {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div><dt style=\"font-size:0.75rem;color:var(--text-tertiary);text-transform:uppercase;margin-bottom:2px;\">Notes</dt><dd style=\"font-size:0.875rem;color:var(--text-secondary);\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var8 string
					templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(data.Report.Notes)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 79, Col: 87}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</dd></div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</dl></div><!-- Resolve Form --><div style=\"background:var(--surface-elevated);border-radius:8px;padding:20px;border:1px solid var(--border-default);\"><h2 style=\"font-size:1rem;font-weight:600;color:var(--text-primary);margin-bottom:16px;\">Take Action</h2>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if data.Report.Status == "UNDER_REVIEW" {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var9 string
					templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs("/moderation/reports/" + data.Report.ID.String() + "/resolve")
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 88, Col: 83}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-swap=\"none\" style=\"display:flex;flex-direction:column;gap:12px;\"><div><label style=\"font-size:0.875rem;font-weight:500;color:var(--text-primary);display:block;margin-bottom:4px;\">Action</label> <select name=\"action_type\" style=\"width:100%;padding:8px;border-radius:6px;border:1px solid var(--border-default);background:var(--surface-primary);color:var(--text-primary);font-size:0.875rem;\"><option value=\"APPROVE\">Approve (no action needed)</option> <option value=\"TAKEDOWN\">Takedown resource</option> <option value=\"WARN\">Warn author</option></select></div><div><label style=\"font-size:0.875rem;font-weight:500;color:var(--text-primary);display:block;margin-bottom:4px;\">Notes</label> <textarea name=\"notes\" rows=\"3\" style=\"width:100%;padding:8px;border-radius:6px;border:1px solid var(--border-default);background:var(--surface-primary);color:var(--text-primary);font-size:0.875rem;resize:vertical;\"></textarea></div><div><label style=\"font-size:0.875rem;font-weight:500;color:var(--text-primary);display:block;margin-bottom:4px;\">Evidence</label> <textarea name=\"evidence\" rows=\"2\" style=\"width:100%;padding:8px;border-radius:6px;border:1px solid var(--border-default);background:var(--surface-primary);color:var(--text-primary);font-size:0.875rem;resize:vertical;\"></textarea></div><button type=\"submit\" style=\"padding:8px 16px;background:var(--accent-primary);color:white;border:none;border-radius:6px;font-size:0.875rem;cursor:pointer;font-weight:500;\">Resolve Report</button></form><form hx-post=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var10 string
					templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs("/moderation/reports/" + data.Report.ID.String() + "/dismiss")
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 107, Col: 83}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-swap=\"none\" style=\"margin-top:12px;\"><input type=\"hidden\" name=\"notes\" value=\"Dismissed as invalid\"> <button type=\"submit\" style=\"padding:8px 16px;background:var(--surface-primary);color:var(--text-secondary);border:1px solid var(--border-default);border-radius:6px;font-size:0.875rem;cursor:pointer;font-weight:500;\">Dismiss Report</button></form>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else if data.Report.Status == "OPEN" {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<form hx-post=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var11 string
					templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs("/moderation/reports/" + data.Report.ID.String() + "/assign")
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 112, Col: 82}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" hx-swap=\"none\"><button type=\"submit\" style=\"padding:8px 16px;background:var(--accent-primary);color:white;border:none;border-radius:6px;font-size:0.875rem;cursor:pointer;font-weight:500;\">Assign to Me</button></form>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p style=\"color:var(--text-tertiary);font-size:0.875rem;\">This report has been ")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var12 string
					templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(data.Report.Status)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/moderation/report_detail.templ`, Line: 116, Col: 105}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(".</p>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><!-- Evidence Chain --> <div style=\"margin-top:24px;background:var(--surface-elevated);border-radius:8px;padding:20px;border:1px solid var(--border-default);\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = EvidenceChain(data.Actions).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base(layouts.PageData{
			Title:       "Report Detail",
			ActiveRoute: "/moderation/reports",
			Username:    data.username(),
			UserRole:    data.userRole(),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
