// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package supplierpages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/eduexchange/eduexchange/internal/middleware"
	"github.com/eduexchange/eduexchange/internal/model"
	supplierservice "github.com/eduexchange/eduexchange/internal/service/supplier"
	"github.com/eduexchange/eduexchange/internal/templ/layouts"
)

// SupplierDetailData holds data for the supplier detail page.
type SupplierDetailData struct {
	Supplier *model.Supplier
	Orders   []model.SupplierOrder
	KPI      *model.SupplierKPI
	IsAdmin  bool
	AuthUser *middleware.AuthUser
}

func (d SupplierDetailData) username() string {
	if d.AuthUser != nil {
		return d.AuthUser.Username
	}
	return ""
}

func (d SupplierDetailData) userRole() string {
	if d.AuthUser != nil && len(d.AuthUser.Roles) > 0 {
		return d.AuthUser.Roles[0]
	}
	return ""
}

func (d SupplierDetailData) contactDisplay() string {
	if d.Supplier == nil {
		return ""
	}
	if d.IsAdmin && d.Supplier.ContactJSON != "" {
		return supplierservice.DecryptContact(d.Supplier.ContactJSON)
	}
	return d.Supplier.ContactMask
}

// SupplierDetailPage renders the supplier detail page.
func SupplierDetailPage(data SupplierDetailData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			if data.Supplier != nil {
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div style=\"margin-bottom:24px;display:flex;align-items:center;justify-content:space-between;\"><div><h1 style=\"font-size:1.5rem;font-weight:700;color:var(--text-primary);\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Supplier.Name)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/supplier/supplier_detail.templ`, Line: 55, Col: 97}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h1><div style=\"margin-top:8px;display:flex;gap:8px;align-items:center;\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = TierBadge(data.Supplier.Tier).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = StatusBadge(data.Supplier.Status).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><a href=\"/suppliers\" style=\"font-size:0.875rem;color:var(--brand-primary);\">← Back to Suppliers</a></div><div style=\"display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-bottom:24px;\"><div style=\"background:var(--surface-elevated);border:1px solid var(--border-default);border-radius:10px;padding:20px;\"><h2 style=\"font-size:1rem;font-weight:600;color:var(--text-primary);margin-bottom:16px;\">Contact Information</h2><div><span style=\"font-size:0.875rem;color:var(--text-secondary);\">Contact: </span> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if data.IsAdmin {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"supplier-contact-full\" style=\"font-size:0.875rem;font-weight:500;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var4 string
					templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(data.contactDisplay())
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/supplier/supplier_detail.templ`, Line: 70, Col: 110}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				} else {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span class=\"supplier-contact-masked\" style=\"font-size:0.875rem;font-weight:500;color:var(--text-tertiary);\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var5 string
					templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(data.Supplier.ContactMask)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/supplier/supplier_detail.templ`, Line: 72, Col: 143}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</span>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if data.KPI != nil {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div style=\"background:var(--surface-elevated);border:1px solid var(--border-default);border-radius:10px;padding:20px;\"><h2 style=\"font-size:1rem;font-weight:600;color:var(--text-primary);margin-bottom:16px;\">Latest KPI Summary</h2><div style=\"display:grid;grid-template-columns:1fr 1fr;gap:12px;\"><div><div style=\"font-size:0.75rem;color:var(--text-secondary);\">OTD</div><div style=\"font-size:1.125rem;font-weight:700;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var6 string
					templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f%%", data.KPI.OnTimeDeliveryPct))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/supplier/supplier_detail.templ`, Line: 83, Col: 108}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div><div style=\"font-size:0.75rem;color:var(--text-secondary);\">Stockout</div><div style=\"font-size:1.125rem;font-weight:700;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var7 string
					templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f%%", data.KPI.StockoutRatePct))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/supplier/supplier_detail.templ`, Line: 87, Col: 106}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div><div style=\"font-size:0.75rem;color:var(--text-secondary);\">Return Rate</div><div style=\"font-size:1.125rem;font-weight:700;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var8 string
					templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f%%", data.KPI.ReturnRatePct))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/supplier/supplier_detail.templ`, Line: 91, Col: 104}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div><div><div style=\"font-size:0.75rem;color:var(--text-secondary);\">Defect Rate</div><div style=\"font-size:1.125rem;font-weight:700;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var9 string
					templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("%.1f%%", data.KPI.DefectRatePct))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/supplier/supplier_detail.templ`, Line: 95, Col: 104}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></div></div><div style=\"margin-top:12px;\"><a href=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var10 templ.SafeURL = templ.SafeURL("/suppliers/" + data.Supplier.ID.String() + "/kpis")
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var10)))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" style=\"font-size:0.875rem;color:var(--brand-primary);\">View Full KPI Dashboard →</a></div></div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><div style=\"background:var(--surface-elevated);border:1px solid var(--border-default);border-radius:10px;overflow:hidden;\"><div style=\"padding:16px 20px;border-bottom:1px solid var(--border-default);display:flex;align-items:center;justify-content:space-between;\"><h2 style=\"font-size:1rem;font-weight:600;color:var(--text-primary);\">Orders</h2>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				if data.IsAdmin {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<a href=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var11 templ.SafeURL = templ.SafeURL("/supplier/orders/new?supplier_id=" + data.Supplier.ID.String())
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var11)))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" style=\"display:inline-flex;align-items:center;padding:6px 14px;background:var(--brand-primary);color:white;border-radius:6px;font-weight:600;font-size:0.8rem;text-decoration:none;\">+ New Order</a>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><table style=\"width:100%;border-collapse:collapse;\"><thead><tr style=\"background:var(--surface-secondary);\"><th style=\"padding:10px 14px;text-align:left;font-size:0.75rem;font-weight:600;text-transform:uppercase;color:var(--text-secondary);\">Order #</th><th style=\"padding:10px 14px;text-align:left;font-size:0.75rem;font-weight:600;text-transform:uppercase;color:var(--text-secondary);\">Status</th><th style=\"padding:10px 14px;text-align:left;font-size:0.75rem;font-weight:600;text-transform:uppercase;color:var(--text-secondary);\">Created</th><th style=\"padding:10px 14px;text-align:left;font-size:0.75rem;font-weight:600;text-transform:uppercase;color:var(--text-secondary);\">Actions</th></tr></thead> <tbody>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, o := range data.Orders {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<tr style=\"border-bottom:1px solid var(--border-default);\"><td style=\"padding:12px 14px;font-size:0.875rem;font-family:monospace;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var12 string
					templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(o.OrderNumber)
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/supplier/supplier_detail.templ`, Line: 124, Col: 95}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</td><td style=\"padding:12px 14px;\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = OrderStatusBadge(o.Status).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</td><td style=\"padding:12px 14px;font-size:0.875rem;color:var(--text-secondary);\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var13 string
					templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(o.CreatedAt.Format("2006-01-02"))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/pages/supplier/supplier_detail.templ`, Line: 128, Col: 120}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</td><td style=\"padding:12px 14px;\"><a href=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var14 templ.SafeURL = templ.SafeURL("/supplier/orders/" + o.ID.String())
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(string(templ_7745c5c3_Var14)))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" style=\"font-size:0.875rem;color:var(--brand-primary);font-weight:500;\">View</a></td></tr>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				if len(data.Orders) == 0 {
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<tr><td colspan=\"4\" style=\"padding:32px;text-align:center;color:var(--text-tertiary);font-size:0.875rem;\">No orders found.</td></tr>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</tbody></table></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Base(layouts.PageData{
			Title:       "Supplier Detail",
			ActiveRoute: "/suppliers",
			Username:    data.username(),
			UserRole:    data.userRole(),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

// OrderStatusBadge renders an order status badge.
func OrderStatusBadge(status model.OrderStatus) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var15 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var15 == nil {
			templ_7745c5c3_Var15 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		switch status {
		case model.OrderStatusCreated:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span style=\"display:inline-flex;padding:2px 8px;border-radius:4px;font-size:0.75rem;font-weight:600;background:#eff6ff;color:#1d4ed8;\">CREATED</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case model.OrderStatusConfirmed:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span style=\"display:inline-flex;padding:2px 8px;border-radius:4px;font-size:0.75rem;font-weight:600;background:#f0fdf4;color:#15803d;\">CONFIRMED</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case model.OrderStatusShipped:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span style=\"display:inline-flex;padding:2px 8px;border-radius:4px;font-size:0.75rem;font-weight:600;background:#f5f3ff;color:#6d28d9;\">SHIPPED</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case model.OrderStatusReceived:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span style=\"display:inline-flex;padding:2px 8px;border-radius:4px;font-size:0.75rem;font-weight:600;background:#fff7ed;color:#c2410c;\">RECEIVED</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case model.OrderStatusQCPassed:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span style=\"display:inline-flex;padding:2px 8px;border-radius:4px;font-size:0.75rem;font-weight:600;background:var(--success-light);color:var(--success);\">QC_PASSED</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case model.OrderStatusQCFailed:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span style=\"display:inline-flex;padding:2px 8px;border-radius:4px;font-size:0.75rem;font-weight:600;background:var(--danger-light);color:var(--danger);\">QC_FAILED</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case model.OrderStatusClosed:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span style=\"display:inline-flex;padding:2px 8px;border-radius:4px;font-size:0.75rem;font-weight:600;background:var(--surface-secondary);color:var(--text-secondary);\">CLOSED</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case model.OrderStatusCancelled:
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<span style=\"display:inline-flex;padding:2px 8px;border-radius:4px;font-size:0.75rem;font-weight:600;background:var(--danger-light);color:var(--danger);\">CANCELLED</span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
