DROP TABLE IF EXISTS resource_reviews CASCADE;
DROP TABLE IF EXISTS bulk_import_jobs CASCADE;
DROP TABLE IF EXISTS resource_files CASCADE;
DROP TABLE IF EXISTS resource_tags CASCADE;
DROP TABLE IF EXISTS resource_versions CASCADE;
DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
