// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/eduexchange/eduexchange/internal/model"

// ToastData holds data for an SSE-pushed notification toast.
type ToastData struct {
	Title     string
	Body      string
	EventType string
}

// toastBorderClass returns the colored left-border class based on event type.
func toastBorderClass(eventType string) string {
	switch model.EventType(eventType) {
	case model.EventAnomalyAlert, model.EventBanNotice:
		return "border-l-4 border-red-500"
	case model.EventEntryDeadline, model.EventReviewDecision, model.EventSupplierQC:
		return "border-l-4 border-amber-500"
	case model.EventBadgeEarned, model.EventLevelUp, model.EventPublishComplete:
		return "border-l-4 border-green-500"
	default:
		return "border-l-4 border-blue-500"
	}
}

// NotificationToast renders a sliding toast notification for SSE-pushed events.
func NotificationToast(d ToastData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{"notification-toast fixed top-4 right-4 z-50 flex items-start gap-3 w-80 bg-white rounded-lg shadow-lg border border-[var(--border-default)] p-4 " + toastBorderClass(d.EventType)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/components/notification_toast.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("\" role=\"alert\"><div class=\"flex-1 min-w-0\"><p class=\"text-sm font-semibold text-[var(--text-primary)]\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(d.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/components/notification_toast.templ`, Line: 33, Col: 72}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><p class=\"text-xs text-[var(--text-secondary)] mt-0.5 line-clamp-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(d.Body)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templ/components/notification_toast.templ`, Line: 34, Col: 79}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p></div><button type=\"button\" class=\"flex-shrink-0 text-[var(--text-tertiary)] hover:text-[var(--text-primary)] transition-colors\" aria-label=\"Dismiss\" onclick=\"(function(btn){var el=btn.closest(&#39;.notification-toast&#39;);if(el){el.style.opacity=&#39;0&#39;;el.style.transform=&#39;translateX(100%)&#39;;el.style.transition=&#39;all 300ms ease-in-out&#39;;setTimeout(function(){el.remove()},300)}})(this)\"><svg class=\"w-4 h-4\" fill=\"none\" stroke=\"currentColor\" viewBox=\"0 0 24 24\"><path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M6 18L18 6M6 6l12 12\"></path></svg></button><script>\n\t\t\t(function() {\n\t\t\t\tvar el = document.currentScript.parentElement;\n\t\t\t\tel.style.transform = 'translateX(100%)';\n\t\t\t\tel.style.opacity = '0';\n\t\t\t\tel.style.transition = 'all 300ms ease-in-out';\n\t\t\t\trequestAnimationFrame(function() {\n\t\t\t\t\tel.style.transform = 'translateX(0)';\n\t\t\t\t\tel.style.opacity = '1';\n\t\t\t\t});\n\t\t\t\tsetTimeout(function() {\n\t\t\t\t\tel.style.opacity = '0';\n\t\t\t\t\tel.style.transform = 'translateX(100%)';\n\t\t\t\t\tsetTimeout(function() { el.remove(); }, 300);\n\t\t\t\t}, 5000);\n\t\t\t})();\n\t\t</script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
